"use client";

import React, { useState } from "react";
import { UploadCloud, CheckCircle, AlertTriangle, Loader2, Database } from "lucide-react";
import { authFetch, API } from "@/lib/authFetch";

export default function LeadScraperUploadPage() {
  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [message, setMessage] = useState<{ text: string; type: "success" | "error" } | null>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
    }
  };

  const handleUpload = async () => {
    if (!file) {
      setMessage({ text: "Please select an Excel file first.", type: "error" });
      return;
    }

    setUploading(true);
    setMessage(null);
    
    const formData = new FormData();
    formData.append("file", file);

    try {
      const response = await authFetch(`${API}/scraped-leads/upload`, {
        method: "POST",
        body: formData,
        // Don't set Content-Type here; browser sets it automatically with the correct boundary
      });

      if (response.ok) {
        const data = await response.json();
        setMessage({ text: `Successfully imported ${data.inserted} leads from Excel!`, type: "success" });
        setFile(null); // Clear file input
      } else {
        const data = await response.json();
        setMessage({ text: data.detail || "Failed to upload leads.", type: "error" });
      }
    } catch (error) {
      setMessage({ text: "Network error occurred while uploading.", type: "error" });
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold flex items-center gap-3">
          <Database className="w-8 h-8 text-blue-600" />
          Import Scraped Leads
        </h1>
        <p className="text-gray-500 mt-2">
          Upload the Excel (.xlsx) file generated by your local Justdial scraper to add leads to the database.
        </p>
      </div>

      <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100 flex flex-col items-center justify-center min-h-[300px]">
        
        <div className="w-full max-w-md">
          <label className="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 hover:bg-gray-100">
            <div className="flex flex-col items-center justify-center pt-5 pb-6">
              <UploadCloud className="w-10 h-10 mb-3 text-gray-400" />
              <p className="mb-2 text-sm text-gray-500"><span className="font-semibold">Click to upload</span> or drag and drop</p>
              <p className="text-xs text-gray-500">.xlsx Excel files only</p>
            </div>
            <input type="file" className="hidden" accept=".xlsx" onChange={handleFileChange} />
          </label>
        </div>

        {file && (
          <div className="mt-4 text-center">
            <p className="text-sm font-medium text-gray-700">Selected file: {file.name}</p>
          </div>
        )}

        <button
          onClick={handleUpload}
          disabled={!file || uploading}
          className="mt-6 flex items-center justify-center px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors font-medium w-full max-w-md"
        >
          {uploading ? (
            <>
              <Loader2 className="w-5 h-5 mr-2 animate-spin" />
              Uploading & Importing...
            </>
          ) : (
            "Upload Leads"
          )}
        </button>

        {message && (
          <div className={`mt-6 p-4 rounded-lg flex items-center gap-3 w-full max-w-md ${
            message.type === "success" ? "bg-green-50 text-green-700 border border-green-200" : "bg-red-50 text-red-700 border border-red-200"
          }`}>
            {message.type === "success" ? (
              <CheckCircle className="w-5 h-5 flex-shrink-0" />
            ) : (
              <AlertTriangle className="w-5 h-5 flex-shrink-0" />
            )}
            <span className="font-medium">{message.text}</span>
          </div>
        )}

      </div>
    </div>
  );
}
